AllCops:
  Exclude:
    - 'lib/version.rb'

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/HashSyntax:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
