AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'lib/rize/version.rb'

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/HashSyntax:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false
